### ISSUE TITLE
Hotload suggestion

### ISSUE THREAD

**Issue by dallinbeutler** [jackmott/monogame-hotload#1]
I like this idea a lot, and I definitely think it's doable. ]
After a little research, I found this:
[Roslyn C# scripting](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples)
It's another idea for hotloading data. It could be used as an immediate source of code execution that gets compiled to the assembly later. Maybe disable VS "edit and continue" and have a file listener looking at the .cs files inside a certain project directory folder and run scripts on that?

**Comment by jackmott** [comment]
Yeah there are interesting possibilities there. Someone will have to experiment to see what kind of workflows are possible, what performance differences there are, if any, etc. I'm pretty happy with the workflow I've get set up as is, but if you want to try ideas out and do a fork we could have branches with different approaches or something.

**Comment by dallinbeutler** [comment]
Alright sounds good.
